### ISSUE TITLE
Can't initiate integration

### ISSUE THREAD

**Issue by KaherdinTristan** [hasl-sensor/integration#58] opened 2023-06-11 05:58 UTC
I've had this integration up and running for a while. But now, it seems to been running into some issues...? 

Upon HA start;

```
This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/hasl3/__init__.py:41
Integration: Swedish Public Transport Sensor (HASL) (documentation, issues)
First occurred: 07:11:28 (1 occurrences)
Last logged: 07:11:28

Unexpected exception importing component custom_components.hasl3
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/hasl3/__init__.py", line 41, in <module>
    @asyncio.coroutine
     ^^^^^^^^^^^^^^^^^
AttributeError: module 'asyncio' has no attribute 'coroutine'

```

```
Logger: homeassistant.setup
Source: setup.py:215
First occurred: 07:11:28 (1 occurrences)
Last logged: 07:11:28

Setup failed for custom integration hasl3: Unable to import component: Exception importing custom_components.hasl3
```

**Comment by DSorlov** [comment] 2023-06-12 09:52
Duplicate of #56

**Closed** 2023-06-12 09:53 UTC
