### ISSUE TITLE
Not able to change configuration from HA Integrations page

### ISSUE THREAD

**Issue by PD75** [hasl-sensor/integration#40] opened 2022-04-11 06:38 UTC
If I try to check the line number or directions and press update, there is no warning but if I configure again the old values are there.

**Comment by DSorlov** [comment] 2022-04-27 11:13
This bug is confirmed. Solution for now is to delete and recrate the sensor. Will be addressed in next release.

**Comment by DSorlov** [comment] 2022-08-12 08:21
Due to stupidity no easy fix. Most seem to have migrated anyways, will close.

**Closed by DSorlov** 2022-08-12 08:21 UTC
Labels: bug
